services:
  - type: web
    name: youtube-clipper
    env: node
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
    healthCheckPath: /health
    autoDeploy: true
    branch: main
    numInstances: 1 