services:
  - type: web
    name: youtube-clipper
    env: node
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: npm run start:simple
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: YTDL_NO_UPDATE
        value: "true"
    healthCheckPath: /health
    autoDeploy: true
    branch: main
    numInstances: 1
    nodeVersion: 20.18.0 